---
- name: Update Varnish Caching option in Wordpress database
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Update wp database.
      command: mysql --user=root --password=B3nmalign312 test -Ns -e "UPDATE wp_options SET varnish_caching_homepage_ttl='30', varnish_caching_ttl='30'"
